method: bayes
metric:
  name: val_accuracy
  goal: maximize
parameters:
  n_conv_blocks:
    values: [1, 2]
  filters_0:
    values: [16, 64, 128, 256]
  filters_sq_1:
    values: [16, 32, 64, 128]
  filters_ex_1:
    values: [64, 128, 256, 512]
  filters_sq_2:
    values: [16, 32, 64, 128]
  filters_ex_2:
    values: [64, 128, 256, 512]
  use_batch_norm:
    values: [True, False]
  dropout:
    values: [0, 0.1, 0.25, 0.5]
  activation:
    values: ['relu', 'gelu', 'elu', 'linear']
  lr:
    values: [1e-2, 1e-3]  # Learning rate values
  batch_size:
    value: 32
  epochs:
    value: 50  # Number of epochs
  l2:
    values: [0, 0.0001, 0.001, 0.01, 0.1]  # L2 regularization values
  resolution:
    value: 256

