method: bayes
metrics:
  - name: val_accuracy
    goal: maximize
parameters:
  n_conv_blocks:
    values: [1, 2, 4, 6]
  n_dense_layers:
    values: [1, 2, 3]
  filters_0:
    values: [8, 16, 32, 64]
  size_0:
    values: [3,5,7]
  pool_size_0:
    values: [2,4]
  filters_1:
    values: [16, 32, 64, 128]
  size_1:
    values: [3,5,7]
  pool_size_1:
    values: [2,4]
  filters_2:
    values: [16, 32, 64, 128]
  size_2:
    values: [3,5,7]
  pool_size_2:
    values: [2,4]
  filters_3:
    values: [32, 64, 128, 256]
  size_3:
    values: [3,5,7]
  pool_size_3:
    values: [2,4]
  filters_4:
    values: [32, 64, 128, 256]
  size_4:
    values: [3,5,7]
  pool_size_4:
    values: [2,4]
  filters_5:
    values: [64, 128, 256, 512]
  size_5:
    values: [3,5,7]
  pool_size_5:
    values: [2,4]
  filters_6:
    values: [64, 128, 256, 512, 1024]
  size_6:
    values: [3,5,7]
  pool_size_6:
    values: [2,4]
  use_batch_norm:
    values: [True, False]
  dropout:
    values: [0, 0.1, 0.25, 0.5]
  activation:
    values: ['relu', 'gelu', 'elu', 'linear']
  activation2:
    values: ['relu', 'gelu', 'elu', 'linear']
  lr:
    values: [1e-2, 1e-3]  # Learning rate values
  momentum:
    values: [0.8, 0.9, 0.99]
  batch_size:
    values: [32, 64]  # Batch size values
  epochs:
    value: 30  # Number of epochs
  optimizer_type:
    values: ['adam', 'sgd']  # Optimizer types
  l2:
    values: [0, 0.0001, 0.001, 0.01, 0.1]  # L2 regularization values
  resolution:
    value: 256

